name: churn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.2
  - numpy=2.0
  - scikit-learn=1.5.1
  - joblib=1.4.2
  - pyyaml=6.0.2
  - matplotlib=3.9
  - uvicorn=0.30.1
  - fastapi=0.111.0
  - pip
  - xgboost=2.0.*
  - pip:
      - streamlit==1.36.0
      - shap==0.45.1
      - kagglehub==0.3.4
